<?php

return [
    /*
    |--------------------------------------------------------------------------
    | ChromaDB Configuration
    |--------------------------------------------------------------------------
    |
    | Configuration for the ChromaDB vector database service.
    | ChromaDB is used for semantic search over knowledge documents
    | using vector embeddings generated by Ollama (nomic-embed-text).
    |
    */

    'host' => env('CHROMADB_HOST', '127.0.0.1'),
    'port' => env('CHROMADB_PORT', 8001),
    'collection' => env('CHROMADB_COLLECTION', 'dona_cake_knowledge'),
    'base_url' => sprintf(
        'http://%s:%s',
        env('CHROMADB_HOST', '127.0.0.1'),
        env('CHROMADB_PORT', 8001)
    ),
];